version: "3.8"
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    image: shop_dev                # tên image bạn muốn
    container_name: shop_dev_mysql # tên container đang chạy
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: todo_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3303:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
